== 50 programs in a week

TIP: http://lafk.pl/QA_Auto_Funicular/NewExercise.html[starting new exercise in steps]

Since quantity is everything here...

. You are to write 50 programs in a week
. Following **Program** definition below

TIP: Karol and Tomek are good reviewers - ask them questions!

=== Definition

Program :: Java program 100% covered by tests

Test :: code that verifies other code, usually written in a framework similar to TestNG

Code coverage :: usually shortened to _coverage_, measure in % of code that is verified (_covered_) with tests

Published program :: program that is available in it's own directory on GitHub repo, where Tomek is made a contributor

=== 50 programs for this week:

EASY

. http://lafk.pl/QA_Auto_Funicular/progText/HelloWorld.html
. http://lafk.pl/QA_Auto_Funicular/progText/HelloName.html
. http://lafk.pl/QA_Auto_Funicular/progText/HelloListOfNames.html
. http://lafk.pl/QA_Auto_Funicular/progText/HelloListOfNamesFromFile.html
. http://lafk.pl/QA_Auto_Funicular/progText/Int2Bin.html
. http://lafk.pl/QA_Auto_Funicular/progText/ITUnitConverter.html
. http://lafk.pl/QA_Auto_Funicular/progText/Rounding.html
. http://lafk.pl/QA_Auto_Funicular/progText/SimpleCurrencyConverter.html
. http://lafk.pl/QA_Auto_Funicular/progText/UnitConverter.html
. http://lafk.pl/QA_Auto_Funicular/progText/StringCountVowels.html
. http://lafk.pl/QA_Auto_Funicular/progText/StringReverse.html
. http://lafk.pl/QA_Auto_Funicular/progText/StringPalindrome.html
. http://lafk.pl/QA_Auto_Funicular/progText/WordCounter.html
. Fizz Buzz / Fizz Buzz (https://en.wikipedia.org/wiki/Fizz_buzz)
. http://lafk.pl/QA_Auto_Funicular/progText/LettersPercentage.html
. http://lafk.pl/QA_Auto_Funicular/progText/DateWithTimezoneToUTCConverter.html
. http://lafk.pl/QA_Auto_Funicular/progText/StringNumbersRegex.html
. http://lafk.pl/QA_Auto_Funicular/progText/DateToDays.html
. http://lafk.pl/QA_Auto_Funicular/progText/LineWrapper.html
. http://lafk.pl/QA_Auto_Funicular/progText/LineUnWrapper.html
. http://lafk.pl/QA_Auto_Funicular/progText/CountEmployees.html
. http://lafk.pl/QA_Auto_Funicular/progText/CreateFile.html
. http://lafk.pl/QA_Auto_Funicular/progText/CreateFileWithContent.html

MEDIUM

. Program zliczający katalogi / Write a program that counts directories
. j.w. + poza takimi z listy (z pliku properties) / Write a program that counts directories except ones from list (list from properties file)
. j.w. + listę można robić ręcznie w programie (wybierz katalogi do…) / Write a program that counts directories except ones from list + directory list can be created manually in the program
. Program zlicza katalogi ORAZ pliki / Program which counts directories and files
. Calculator
. Number sorter
. Number sorter with extra criterias
. Word completion (ext → extra, extramarital, extraterrestrial…)
. A guessing game
. War (card game)
. Usuwanie n-tego elementu z listy (własna struktura dla węzła, bez korzystania np z LinkedList). / Remove nth element from the list (you have your own node structure)
. Sprawdzanie czy każdy nawias otwierający ma odpowiadający nawias zamykający / Check if every opening bracket has corresponding closing bracket
. Zamówienia [dodajesz zamówienie i ilość, na koniec oblicza kwote, może być z rabatami typu przy kupnie 3 produktów A płacisz X zamiast 3 * Y] / Orders [You can add a product and quantity and at the end it calculates amount you need to pay. There can be a special offers, e.g. for three products “A” you pay X instead of 3 * Y where Y is a price of the product “A”]
. Poker Hand Evaluator (You have five cards, what poker hand it is?)
. Walidator hasła na podstawie kilku warunków (długość, znaki specjalne, małe/wielkie litery, cyfry itd). / Password validator based on several conditions (length, special characters, big/small letters, digits, etc)
. Słowny wąż (Marek na jarmarek kupił sobie zegarek) / Word snake
. Text to CSV converter
. Program wyświetlający zawartość pliku podanego po nazwie / Program that displays content of file which name was provided
. Otrzymywanie powiadomień o zasubskrybowanym użytkowniku (prosty obserwator)/ Getting notifications about subscribed user (simple observer pattern)

HARD

. Program walidujący HTMLa za pomocą istniejącego walidatora / Program that validates HTML using existing validator
. Prosty MD → HTML / Simple Markdown to HTML converter
. Prosty walidator HTML 5 HEAD / Simple HTML 5 HEAD validator
. Prosty walidator HTML 5 / Simple HTML 5 validator
. Linia komend (powiedzmy 2 operacje: przechodzenie do kolejnego katalogu i
listowanie plików w katalogu)./ command line (2 operations: changing directory,
listing files in a directory)
. Oto plansza szachów, oblicz "pozycje szachowe" (liczbowa wartość białych i czarnych) / You have a chess board, calculate “chess positions” (numerical value of white and black figures)
. Oto plansza szachów, wykonaj legalny ruch / You have a chess board, make legal move
. Oto plansza szachów, podaj zagrożone figury / You have a chess board, show threatened figures
. Mając podaną figurę wypisz jej ruchy / You have a figure, show its possible moves

IMPOSSIBLE

. http://lafk.pl/QA_Auto_Funicular/progText/Chess.html
. http://lafk.pl/QA_Auto_Funicular/progText/OX.html
. http://lafk.pl/QA_Auto_Funicular/progText/Snake.html

=== Karol and Tomek

Implement five from:

. My books reviews
. OOP OX 
. Rock, paper, scissors
. Agile Planning Poker app
. Simple Orthodox File Manager
. File Editor
. Currency Converter
. Bridge core
. DuckDuckGo search query
. Trello via REST automation

Rules are 'a tad' different: 

. web-app (use Spring Boot, Dropwizard or Ratpack)
. Gradle for build
. each program has own repo
. test coverage: 33% minimum
. suitable for extension later
