# New exercise in steps

[CAUTION]
.Empty repo or there'll be problems
====
Create **EMPTY** GitHub repository! 
No files - do NOT initialize it with README, license or anything!
Otherwise you will have problems with `git push` or `git pull`.

TIP: if you have, try `git pull origin master --allow-unrelated-histories` and press `:wq` in the window that comes after.
====

. choose your exercise
. create new directory for it
. go to that directory
. open terminal there
. `gradle init --type java-application --test-framework testng`
. check that gradle initialized well
. `git init`
. create .gitignore file (see below)
. import the project in your IDE (differs per IDE, so no universal description)
. modify the default gradle App and AppTest so they are yours and fit the exercise
. `git add .`
. `git status`
.. this should have both App.java, AppTest.java, necessary gradle files and .gitignore
.. this should **NOT** have 
... neither dirs like `.gradle`, `.idea` or `.settings`
... nor any files like: `.class`, `.iml`, `.classpath`, `.project` 
. `git commit -m "here you need to give some meaningful description"`
. now go to GitHub and create a repository (**EMPTY!!** as you have been cautioned at the top of the page)
. copy it's clone link (green button saying Clone or Download)
. in your terminal, in a dir with your repo: `git remote add origin LINK_HERE`
. `git push -u origin master`
. your repository now should have your files

## Ignoring files in Git

Below is a file that (if saved as .gitignore in top dir of your project) will ignore all files that are created by NetBeans, Intellij Idea, Java, Gradle and/or Eclipse that you should NOT push to repository.

----
*.iml
.idea/
test-output/
# Created by https://www.gitignore.io/api/java,intellij,eclipse,netbeans,gradle

### Gradle ###
.gradle
/build/

# Ignore Gradle GUI config
gradle-app.setting

# Avoid ignoring Gradle wrapper jar file (.jar files are usually ignored)
!gradle-wrapper.jar

# Cache of project
.gradletasknamecache

# # Work around https://youtrack.jetbrains.com/issue/IDEA-116898
# gradle/wrapper/gradle-wrapper.properties


### Eclipse ###

.metadata
bin/
tmp/
*.tmp
*.bak
*.swp
*~.nib
local.properties
.settings/
.loadpath
.recommenders

# Eclipse Core
.project

# External tool builders
.externalToolBuilders/

# Locally stored "Eclipse launch configurations"
*.launch

# PyDev specific (Python IDE for Eclipse)
*.pydevproject

# CDT-specific (C/C++ Development Tooling)
.cproject

# JDT-specific (Eclipse Java Development Tools)
.classpath

# Java annotation processor (APT)
.factorypath

# PDT-specific (PHP Development Tools)
.buildpath

# sbteclipse plugin
.target

# Tern plugin
.tern-project

# TeXlipse plugin
.texlipse

# STS (Spring Tool Suite)
.springBeans

# Code Recommenders
.recommenders/

### Intellij ###
# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio and Webstorm
# Reference: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

# User-specific stuff:
.idea/workspace.xml
.idea/tasks.xml

# Sensitive or high-churn files:
.idea/dataSources/
.idea/dataSources.ids
.idea/dataSources.xml
.idea/dataSources.local.xml
.idea/sqlDataSources.xml
.idea/dynamic.xml
.idea/uiDesigner.xml

# Gradle:
.idea/gradle.xml
.idea/libraries

# Mongo Explorer plugin:
.idea/mongoSettings.xml

## File-based project format:
*.iws

## Plugin-specific files:

# IntelliJ
/out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

### Intellij Patch ###
# Comment Reason: https://github.com/joeblau/gitignore.io/issues/186#issuecomment-215987721

# *.iml
# modules.xml
# .idea/misc.xml
# *.ipr

### Java ###
*.class

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.ear

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*

### NetBeans ###
nbproject/private/
build/
nbbuild/
dist/
nbdist/
.nb-gradle/

# End of https://www.gitignore.io/api/java,intellij,eclipse,netbeans
----
