/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import hellos.HelloName;
import org.testng.annotations.*;

import java.io.ByteArrayInputStream;

import static org.testng.Assert.*;

public class HelloNameTests {

    @DataProvider(name="names")
    public Object[][] names() {
        return new Object[][] {
            {"Steven"},
            {"Steve"},
            {"Stefan"},
            {"Stephanie"}
        };
    }

    @Test(dataProvider = "names")
    public void appGreetsByName(String name) {
        HelloName classUnderTest = new HelloName();
        assertEquals(classUnderTest.getGreeting(name), "Hello "+name, "app should greet by name");
    }

    @Test public void whetherGreetedNameIsTheOneWeHaveGiven() {
      // given
        HelloName a = new HelloName();
        System.setIn(new ByteArrayInputStream("A fancy name".getBytes()));
        String nameWeGave = a.askUserForAName();
        // when
        String nameWeGreet = a.getGreeting(nameWeGave);

      // then
        assertEquals(nameWeGreet, "Hello " + nameWeGave);
    }


}
